export const EVENT_TYPES = {
  TICK: 'TICK',
  SIGNAL: 'SIGNAL',
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_CANCELED: 'ORDER_CANCELED',
  CONTEXT_UPDATED: 'CONTEXT_UPDATED',
} as const

export const ORDER_SIDE = {
  BUY: 'BUY',
  SELL: 'SELL'
} as const

export const ORDER_TYPE = {
  MARKET: 'MARKET',
  LIMIT: 'LIMIT',
  STOP: 'STOP',
  STOP_LIMIT: 'STOP_LIMIT',
  TRAILING_STOP: 'TRAILING_STOP',
} as const

export const ORDER_STATUS = {
  NEW: 'NEW',
  FILLED: 'FILLED',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED'
} as const

export const TIME_IN_FORCE = {
  DAY: 'DAY',
  GTC: 'GTC',
  OPG: 'OPG',
  CLS: 'CLS',
  IOC: 'IOC',
  FOK: 'FOK',
} as const

export const SORT_DIRECTION = {
  ASC: 'ASC',
  DESC: 'DESC',
}